name: third_eye
description: Third eye APP.

publish_to: "none"

version: 2.0.0+76

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
  animations: ^2.0.7
  shared_preferences: ^2.0.17  
  camera: ^0.10.3
  just_audio: ^0.9.31
  audio_video_progress_bar: ^1.0.0
  rxdart: ^0.27.7
  google_mlkit_object_detection: ^0.6.0
  permission_handler: any
  google_mlkit_text_recognition: ^0.5.0
  flutter_vibrate: ^1.3.0
  flutter_tts: ^3.6.3
  dio: ^5.0.1
  flashlight: ^0.1.1
  get: ^4.6.5
  cookie_jar: ^4.0.1
  dio_cookie_manager: ^3.0.0
  connectivity_plus: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  flutter_accessibility_service: ^0.2.1
  flutter_tflite: ^1.0.1
  flutter_launcher_icons: ^0.10.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  #flutter_pdfview: ^1.3.1
  flutter_vision: ^1.1.1
  url_launcher: ^6.1.11
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.2.0
  firebase_core: ^2.21.0
  firebase_analytics: ^10.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/models/
    - assets/banners/
   # - assets/pdf/
    - assets/vision/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/launcher_icon.png"
  min_sdk_android: 21

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100

    - family: RobotMono
      fonts:
        - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf

    - family: Arial
      fonts:
        - asset: assets/fonts/ARIAL.TTF
